### ISSUE TITLE
Just a question... 

### ISSUE THREAD

**Issue by dphoebus** [DagonMetric/ng-config#226]
I'm sorry if this is just that obvious but I am having a hard time figuring out how to correctly update any config values.

I have the latest version (v4.0) and I have the service working as expected.  Values are retrieved from an API and I can pull them from the ConfigService but updating the object returned does not trigger the EventEmitter and I don't see a method to call on the ConfigService that would take my updated data and update the underlying option.

``` typescript
this.form.valueChanges
    .pipe(takeUntil(this._unsubscribeAll))
    .subscribe((formValues) => {
         let options = <AppOptions>this._configService.getValue('app');
         options.layout.width = formValues.layout.width;

        // What do I do here?
    });
```
Again, sorry if this is obvious but I'm missing it.  Thank you for your time.

**Comment by dagonmetric-contributor** [comment]
The problem may be
* You are using _this.form.valueChanges..._ instead of **this._configService.valueChanges...**

## Use Case Scenario

* Whenever value changes in remote config, call ` this.configService.reload().subscribe(() => {....});`` to reload fresh config values.
* `this._configService.valueChanges` will only trigger when **this._configService.reload()...** is called and any config value is changed.

More information about ConfigService api, please see [ConfigService wiki](https://github.com/DagonMetric/ng-config/wiki/ConfigService)

**Comment by dphoebus** [comment]
Hey, thanks for the clarification.  Nice work on the library and thanks for your time.
